server:
  port: 8080

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway

spring:
  application.name: boosting-gateway
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: cloud-server-id
          uri: lb://cloud-server
          predicates:
            Path=/cloud/**
          filters:
            - AuthFilter
        - id: writer-service-id
          uri: lb://writer-service
          predicates:
            Path=/writer/**
          filters:
            - AuthFilter
        - id: users-service-id
          uri: lb://user-service
          predicates:
            Path=/users/
        - id: blog-service-id
          uri: lb://blog-service
          predicates:
            Path=/blog-service/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
